- .github/release.drafter.yml
- .github/workflows/release_drafter.yml
- .github/workflows/semantic_pr_check.yml
This adds two new CI workflows:
1. Auto-release drafter. After PRs are merged, a release draft is created automatically.
2. Semantic PR Titles checker. PRs are required to follow the semantic PRs convention, which is basically the conventional commit spec, adapted to PRs.
> CI: Add auto-release draft

- README.md
- airbyte/exceptions.py
- docs/generate.py
This significantly cleans up the docs:
1. Add logo and favicon.
2. Landing page is now the module index.
3. Added search capability.
4. Fixed some renames that were missed previously.
5. Add 'show source' option on docs.
> Docs: Cleanup auto-generated reference docs

- README.md
This removes the changelog and points users instead to the release notes page.
> Chore: Replace changelog with link to GitHub Releases

- .github/workflows/python_lint.yml
- airbyte/_factories/connector_factories.py
- airbyte/source.py
This PR allows a more streamlined single-step source creation and setup.
Instead of requiring multiple steps:
```py
source = ab.get_source(
"source-github",
config=GITHUB_CONFIG,
)
source.select_streams(["pull_requests", "issues"])
read_result = source.read()
```
We can now do all in a single step:
```py
read_result = ab.get_source(
"source-github",
config=GITHUB_CONFIG,
streams=["pull_requests", "issues"],
).read()
```
If `"*"` is specified, it will be treated as "all", equivalent to `select_all_streams()`.
For tutorials, the multi-step process is often preferable, because it allows each step to be debugged in turn. However, for demos, the reverse is true: fewer lines and fewer statement makes the process easier to read and easier to understand overall.
This also allows streams to be …
> Feat: Streamline stream selection and support for `select_streams("*")`

- examples/run_integ_test_source.py
~~This is not yet tested, and needs a bit more work.~~
This is working now. 😄 
The goal here is to be able to run a sync using any source by running the script and passing the name of the source you want to test:
```
poetry run python examples/run_integ_test_source.py SOURCE_NAME
```
Or to test a specific stream:
```bash
poetry run python examples/run_integ_test_source.py SOURCE_NAME STREAMS_CSV
```
If provided, the second `STREAMS_CSV` arg is expected to be a comma-delimited string (not a file) with one or more streams. For instance: `events` (with no comma) or `events,customers,users`.
For instance, here are the commands I used for testing Source Klaviyo:
```bash
poetry run python examples/run_integ_test_source.py source-klaviyo
poetry run python examples/run_integ_test_source.py …
```
> Test: Add script to streamline integ test with any source

- airbyte/_file_writers/__init__.py
- airbyte/_file_writers/jsonl.py
- airbyte/_file_writers/parquet.py
- airbyte/_processors.py
- airbyte/caches/base.py
- airbyte/caches/duckdb.py
- airbyte/caches/postgres.py
- airbyte/caches/snowflake.py
- airbyte/types.py
- tests/integration_tests/test_source_test_fixture.py
- tests/unit_tests/test_caches.py
Add Jsonl file writer.
This file writer better supports variable schemas that were breaking the Parquet writer.
> Feat: Replace Parquet File Writer with Gzipped Jsonl File Writer

- airbyte/_factories/connector_factories.py
Found this bug while creating a notebook for langchain. The `streams` arg of `get_source()` was only passed to the first constructor and not the second one in that factory function.
This simply fixes that omissiong.
Tested on a Colab notebook to confirm the fix:
- https://colab.research.google.com/drive/1IiP224qBttdSVYA31mutgokDsMk-1DAq#scrollTo=8sJRgmsinjPK
> Fix: Pass `streams` list from `get_source()` to `Source` constructor

- .gitignore
If we run `connectors_ci`, it will create these directories. This PR ensures we keep git history safe from accidentally committed secrets in `secrets` or `.secrets` dirs.
> Chore: Add `.gitignore` rules for secrets dirs

- .github/workflows/python_pytest.yml
- airbyte/_util/document_rendering.py
- airbyte/caches/base.py
- airbyte/caches/duckdb.py
- airbyte/documents.py
- examples/run_file_source.py
- pyproject.toml
- tests/conftest.py
- tests/integration_tests/fixtures/source-broken/setup.py
- tests/integration_tests/fixtures/source-broken/source_broken/run.py
- tests/integration_tests/fixtures/source-test/setup.py
- tests/integration_tests/fixtures/source-test/source_test/run.py
- tests/integration_tests/test_install.py
- tests/integration_tests/test_snowflake_cache.py
- tests/integration_tests/test_source_test_fixture.py
- tests/integration_tests/test_validation.py
- tests/lint_tests/test_mypy.py
- tests/lint_tests/test_ruff.py
- tests/unit_tests/test_anonymous_usage_stats.py
- tests/unit_tests/test_caches.py
- tests/unit_tests/test_exceptions.py
- tests/unit_tests/test_pip_helpers.py
- tests/unit_tests/test_progress.py
- tests/unit_tests/test_type_translation.py
This adds Python 3.9 and 3.11 back into the test matrix.
Findings:
- Python 3.11 worked without any issue.
- Python 3.9 was failing because Pydantic wants to parse/evaluate type hints for classes derived from `pydantic.BaseModel`.
- I disabled the lint rule that dissallowed the legacy syntaxes `Union[x | y]` and `Optional[x]`.
- In any subclasses of `BaseModel`, I reverted to legacy-style syntax declarations, to appease the Pydantic eval statements.
> Fix: Resolve Python 3.9 compatibility issues, expand CI test matrix

- poetry.lock
- pyproject.toml
Resolves: #35 
In the latest version, complains about version conflicts and asks users to reload the Notebook.
This PR aims to widen supported versions for `google.auth` and `pandas`, to avoid conflicts with the default Colab environment.
> Chore: Loosen version requirements to match Colab defaults

- airbyte/types.py
- tests/unit_tests/test_type_translation.py
Resolves: #101 
Method (TDD):
1. First I added tests based on the reported issue.
2. Confirmed that tests were failing in the same manner as described in the issue.
3. Added handling to fix tests.
> Fix: Handle array types with json schema parsing errors in subtypes

- airbyte/caches/bigquery.py
- airbyte/caches/duckdb.py
- airbyte/caches/motherduck.py
- airbyte/caches/postgres.py
- airbyte/caches/snowflake.py
These usage samples will render at the top of each cache's module reference page.
This was very quick to create. I started it accidentally when recording my last loom. Most of the example code was written by copilot actually. 😄 🤖
> Docs: Add usage samples for each cache option

- .github/workflows/autofix.yml
- .github/workflows/pydoc_preview.yml
- .github/workflows/pydoc_publish.yml
- .github/workflows/pypi_publish.yml
- .github/workflows/python_lint.yml
- .github/workflows/python_pytest.yml
- .github/workflows/release_drafter.yml
- .github/workflows/semantic_pr_check.yml
- .github/workflows/slash_command_dispatch.yml
- airbyte/_util/telemetry.py
- tests/unit_tests/test_anonymous_usage_stats.py
This is ready for review.
1. On first run, PyAirbyte will check for an existing analytics file.
2. If not found, and if `DO_NOT_TRACK` is not set, a new ID will be generated and will be stored in a yaml file at `~/.airbyte/analytics.yml`
3. If `AIRBYTE_ANALYTICS_ID` env var is set, then the provided ID will be used instead of a randomly generated one. In this case, the provided analytics ID will also be saved to the analytics file, overriding any previously set value.
4. This PR updates all of our CI jobs to pass in a (newly created) repository variable ([here](https://github.com/airbytehq/PyAirbyte/settings/variables/actions)), which contains a newly generated ULID that is specific to our CI flows.
> Chore: Add anonymous user ID in tracking events

- airbyte/_util/meta.py
- airbyte/_util/telemetry.py
An overly simple implementation, admittedly, but a decent start that should work as expected in most cases.
Note: I haven't tested this yet. I may try manually testing in a notebook.
> Chore: Add telemetry tracking flag for `langchain-airbyte`, fix incorrect telemetry URL in first-time execution

- airbyte/exceptions.py
- airbyte/sources/base.py
Resolves #126 
When connectors fail due to incorrect config, they often do not do so gracefully.
This update will make pre-validation of config the default behavior, which gives us more control over the user experience.
> Feat: Always run config pre-validation

- airbyte/_util/meta.py
This fixes a parsing issue which prevents detection of the notebook name in Colab environments.
(Auto-merge enabled.)
> Fix: Resolve bug in Colab notebook name detection

- airbyte/sources/base.py
- airbyte/warnings.py
This is discouraged in normal situations, but there are valid use cases.
The use case brought up [in slack](https://airbytehq-team.slack.com/archives/C06FZ238P8W/p1710823746305029?thread_ts=1710320283.398979&cid=C06FZ238P8W) was an SQS queue - wherein we want to process only new records and not already-seen records.
> Feat: Allow incremental refresh with replace strategy

- airbyte/_processors/sql/base.py
- airbyte/sources/base.py
- examples/run_faker_to_motherduck.py
- examples/run_snowflake_faker.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/integration_tests/test_all_cache_types.py
A small update. This brings back the print of processed stream names.
For example:
```
Read Progress                                                                              
Started reading at 23:31:01.                                                                                                                                            
Read 20,100 records over 2 seconds (10,050.0 records / second).                                                                                                         
Wrote 20,100 records over 3 batches.                                                                                                                                    
Finished reading at 23:31:03. …
```
> Fix: Improve progress updates, including list of streams finalized

- .github/workflows/on-demand-pr-test-command.yml
- .github/workflows/python_pytest.yml
- .github/workflows/slash_command_dispatch.yml
- .github/workflows/test-pr-command.yml
Add a CI test to ensure that all tests that require creds are correctly marked with the `pytest.mark.requires_creds` decorator. Otherwise, those tests will fail in this new workflow.
> CI: Add 'no-creds' test in CI, fix "only on forks" condition of full pytest suite

- airbyte/_processors/sql/base.py
Fixes #148 
I dug a bit around and found out, that the Problem was, that the schema name was missing in the final swaping. I just added the method used at other places to add the schema.
I separated the statements in several lines so that i won't go over the defined Line Limit from 100.
Tests were all successful except for the integration Tests of some caches, since i don't have access to them.
Also tested the fix manuallay with the pokeapi source and the linkedinpages source mentioned in #148. Everything worked and data was in the final tables.
> Fix: Add schema in Postgres Cache to swapping method

- README.md
Raised in slack...
We renamed `get_connection` to `get_source` but missed the update of this reference in docs.
> Docs: Fix renamed 'get_connection'

- airbyte/_util/telemetry.py
As this file is going to be used by more than simply `PyAirbyte`, replace the `PyAirbyte` reference with `Airbyte`.
> Chore: Update user-facing header to be more inclusive in `analytics.yml`

- .github/workflows/python_pytest.yml
- tests/lint_tests/test_mypy.py
- tests/lint_tests/test_ruff.py
We have lint checks in pytest so that developers can see in one place whether their code is ready to push.
However, in CI, we have a dedicated lint job and it is redundant to show these results also in the pytest jobs.
If there is a lint/format problem, but if all other tests are successful, this change will show pytest tests as 'green' and only the lint/format jobs will show as red. This helps the developer know what is needed at-a-glance, without having to jump into pytest logs when all other tests are fine.
> CI: Skip lint checks in pytest when redundant

- airbyte/__init__.py
- airbyte/_processors/file/base.py
- airbyte/_processors/file/jsonl.py
- airbyte/_util/name_normalizers.py
- airbyte/records.py
- airbyte/sources/base.py
- tests/unit_tests/test_text_normalization.py
Following from:
- #14 
This PR simply moves the class to a public module and adds user-facing reference documentation.
> Docs: Move `StreamRecord` class to public module, add docs

- pyproject.toml
The only meaningful change is adding `tool.pyright` config in `pyproject.toml`, so that PyRight can see the `.venv` and resolve imports.
Side-effect: formatted pyproject.toml. 
I don't have a _very_ strong opinion. This makes _my_ life easier as Zed doesn't do mypy. But, mypy and Pyright are not quite the same and have slighly different rules, and using PyRight should not be endorsed, and/or Pyright correctness is not guaranteed as far as I understand.
But, I don't think this will hurt us in any way. ;)
> Chore(tools): Align Pyright configuration with MyPy and specific deterministic venv location for Pyright

- airbyte/_processors/sql/snowflake.py
It seems snowflake doesn't like to run multiple queries with a `PUT` statement on it.
```
Error when executing SQL:
PUT 'file:///Users/sebastienhaentjens/Documents/pyairbyte/.cache/job_posts_01HV6X9KE5NHAW5R4VPA7N4WMB.jsonl.gz' @%job_posts_01hv6xc3bgypcpsh709wk1d4mf;
PUT 'file:///Users/sebastienhaentjens/Documents/pyairbyte/.cache/job_posts_01HV6XC3BG0Q5NY66CYW4QWSBX.jsonl.gz' @%job_posts_01hv6xc3bgypcpsh709wk1d4mf;
ProgrammingError(snowflake.connector.errors.ProgrammingError) 100132 (P0000): JavaScript execution error: Uncaught Execution of multiple statements failed on 
statement "PUT 'file:///Users/sebastienha..." (at line 1, position 0).
Stored procedure execution error: Unsupported statement type 'PUT_FILES'. in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed …
```
> Fix: Resolve load issue by running Snowflake`PUT` queries sequentially

- airbyte/secrets/google_gsm.py
- tests/integration_tests/secrets/test_gsm_secrets.py
We were lacking integration tests for the GSM-based secret fetching (by label and connector).
This PR adds needed integration tests and fixes bugs that otherwise prevent successful retrieval.
This also adds a singular `fetch_connector_secret()` which just gives the first secret that would be returned by `fetch_connector_secrets()`.
> Feat: Add singular `fetch_connector_secret()` for `GoogleGSMSecretManager`, fix GSM edge cases, and add CI tests

- airbyte/_processors/sql/duckdb.py
- airbyte/types.py
- tests/integration_tests/fixtures/source-test/source_test/run.py
- tests/integration_tests/test_source_test_fixture.py
Resolves: #177
- #177
~~Note: The choice of `DECIMAL(38, 10)` is somewhat arbitrary, but it forces use of a large internal (int) data type in DuckDB, and it should be big enough (28 digits) on the left side of the decimal while also providing a meaningful amount of precision on the right side (10 digits).~~
After some digging, I found that Java destinations prefer scale of `9`: `DECIMAL(38, 9)`.
I've updated the PR to use this size.
----
Per internal slack inquiry: https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1713209219674449?thread_ts=1713208569.977779&cid=C03C4AVJWG4
Relevant code on the Java side:
https://github.com/airbytehq/airbyte/blob/d8e8a0dab4d951fb39ab2fb7048d167f096948c2/airbyte-cdk/java/airbyte-cdk/db-destinations/src/main/kotlin/io/airbyte/cdk/integrations/destinatio …
> Fix: Expand default decimal size to `(38, 9)` to resolve issues with large number values

- .github/workflows/fix-pr-command.yml
- .github/workflows/test-pr-command.yml
Fixes two isses:
- auto-commits didn't previously trigger a new set of CI workflows
- optional comment-id fields were not actually optional when invoking manually with workflow dispatch
> CI: Fix minor issues in on-demand test and format workflows

- airbyte/_executor.py
- airbyte/sources/base.py
- tests/integration_tests/test_source_test_fixture.py
Allows users to detect the version number of a source connector.
Relates to:
- https://github.com/airbytehq/PyAirbyte/issues/212
> Feat: Add `Source.connector_version` property

- airbyte/_executor.py
- airbyte/sources/util.py
- tests/conftest.py
- tests/integration_tests/test_docker_executable.py
Adding a `DockerExecutor` class to the `get_source` factory. 
I absolutely love this library as it allows me to rapidly pull data from a variety of different sources and load them into a "local DW" in duckDB for quick analysis using SQL. All this without having to deploy or startup any servers!! However, on numerous occasions I needed to pull in data from Java based Airbyte sources such as PostgreSQL and MySQL and couldn't use PyAirbyte to do that. Therefore, it would be great if the library supported the execution of Docker images that adhere to the Airbyte protocol. This will greatly increase the number of compatible sources and allow users to develop additional sources in their language of choice.
`DockerExecutor` is almost identical to `PathExecutor` but instead of receiving a path to …
> Feat: Add an Executor for Docker sources

- airbyte/__init__.py
- airbyte/experimental/__init__.py
- airbyte/sources/util.py
This PR moves the newly-expanded `get_source` implementation into a new `airbyte.experimental` module, and it reverts the default `get_source` implementation to not support Docker (yet).
Also, I've renamed the argument from `docker_executor` (`bool`) to `docker_image` which can be `bool` (`True`) _or_ it can be a string naming the docker image, with an optional tag.
> Feat: Accept docker image names, move `DockerExecutor` support to `experimental` module

- .github/workflows/autofix.yml
- .github/workflows/fix-pr-command.yml
- .github/workflows/pydoc_preview.yml
- .github/workflows/pydoc_publish.yml
- .github/workflows/python_lint.yml
- .github/workflows/python_pytest.yml
- .github/workflows/test-pr-command.yml
- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
This adds support for the following `Poe` tasks:
```bash
poe test
poe coverage
poe coverage-report
poe coverage-html
poe check
poe fix
poe fix-and-check
poe fix-unsafe
```
All of the above can be run via `poetry run poe` if you don't have the poetry environment activated and/or if you don't want to pre-install Poe.
The recommendation is to install poe on your local workstation like this:
```bash
pipx install poe
```
and then you will always be able to just write `poe ...` without having to type `poetry run`.
As noted above, you can quickly see coverate reports by running the following locally:
```bash
poe coverage-html
```
You can also find coverage reports uploaded as artifacts on each CI test run.
Coverage reports are under the [Summary …
> Chore: Add Poe task support and code coverage reporting

- .github/workflows/poetry-lock-command.yml
- .github/workflows/slash_command_dispatch.yml
This adds a new `/poetry-lock` slash command. It copies all code from the `/fix-pr` slash command, and adapts it slightly for this use case.
> **[Note]**
> This is in auto-merge status, ready to merge on approval.
> CI: Add '/poetry-lock' slash command

- airbyte/_future_cdk/sql_processor.py
- airbyte/_processors/sql/snowflakecortex.py
This brings together the logic from the old "ensure_compatible_schema" implementation with the newer "add_missing_columns".
When we added the "add_missing_columns" functionality, we neglected to update/incorporate the prior implementation.
> Chore: Clean up missing column additions logic

- airbyte/types.py
- tests/integration_tests/fixtures/source-test/source_test/run.py
- tests/integration_tests/test_source_test_fixture.py
- tests/unit_tests/test_type_translation.py
A fix for #244.
This is smaller scope than:
- https://github.com/airbytehq/PyAirbyte/pull/246
In that PR, we modify the failover type to be `object`/`JSON`/`VARIANT` for cases of `anyOf(string, object)`. In this case, we don't change anything except to make sure that the expected exception is raised - and this triggers the expected failsafe behavior, without changing it.
> Fix: Resolve error `TypeError` "unhashable type list" (2nd pass)

- airbyte/_util/meta.py
Catch exceptions and return False to better support ASGI runtimes
> Fix: Wrap is_interactive checks in an exception handler 

- airbyte/_future_cdk/sql_processor.py
- airbyte/_processors/sql/bigquery.py
- airbyte/_processors/sql/snowflake.py
- airbyte/constants.py
This reverts back to `airbyte_raw` as the default schema name.
Some database types lost this default when we refactored in either `0.10.x` or `0.11.x`.
Anyone who is providing an explicit schema name will not be affected by this change.
⚠️ Set to auto-merge
> Fix: Add back default schema name `'airbyte_raw'` for caches

- airbyte/records.py
- poetry.lock
- pyproject.toml
- Improved unique ID generation by switching from ULID to a custom UUID method, ensuring more robust and unique identifier creation.
Chores
- Updated dependencies in pyproject.toml, including the addition of the uuid7 and types-pyyaml packages, while removing ulid.
In the previous flamegraph, the ULID creation was taking approx. 4us, plus up to 5us to convert to `str` type. The `UUID v7` implementation generates a UUID in one step in approx 2us. This cuts off approximately 7us out of ~26us processing time per record, or up to 30% of the per-record processing time.
Now (2us of 19us total):
Previous (4+5us, combined 9us of 27us total):
Notes:
- ULIDs are still used for batch IDs, file name suffixes, and table name suffixes. This change only affects unique record IDs.
- In working this PR, I …
> Feat: Replace ULID raw record ID with UUID v7

- .github/workflows/test-pr-command.yml
Replace the personal access token with a GitHub App token for improved security and explicitly define the repository owner in the CI configuration.
> ci: Use GitHub App token for CI workflow
